### PR TITLE
Fix throwOnError option

### LINKED ISSUE #7: Cannot set throwOnError
It appears that throwOnError is a property on internalOptions but there does not appear to be any way to set that. Am I missing something?

### PR DESCRIPTION
**Pull request by BrianSipple**
This PR fixes #7. It turns out there are 2 reasons that `throwOnError` was never being called:

1) In `postProcess`, we’re attempting to [read `throwOnError` from `this.internalOptions`](https://github.com/ember-cli/broccoli-lint-eslint/pull/44/files#diff-6d186b954a58d5bb740f73d84fe39073L183), which is actually `this.options`, so we never find it. That said, `internalOptions` does seem to be the clearer name (we’re working with both options for Broccoli and [options for ESLint](https://github.com/ember-cli/broccoli-lint-eslint/pull/44/files#diff-6d186b954a58d5bb740f73d84fe39073L91) — which, in the constructor, are set on... well... `options.options`), so I changed the `this.options` property that’s initialized in the constructor to `this.internalOptions`.

2) Once we do manage to detect the `throwOnError` setting, the [wrong input is being sent to `getResultSeverity`](https://github.com/ember-cli/broccoli-lint-eslint/pull/44/files#diff-6d186b954a58d5bb740f73d84fe39073L182), and so we never detect an `error` level violation. Passing in list of `messages` found on the first item in `report.results` here does the trick. (The test that allowed me to discover this can be played with [here](https://github.com/ember-cli/broccoli-lint-eslint/pull/44/files#diff-7f3bc9926f924d6bcc2b3573c4dfb89eR245).)

### CODE REVIEW

**Comment by BrianSipple** [comment]
Friendly ping (cc @alexlafroscia, @Turbo87, @rwjblue) if anyone wants to take another look at this, but -- if not anything else -- I don't want to keep being a blocker for https://github.com/ember-cli/ember-cli-eslint/pull/93.

**Comment by alexlafroscia** [comment]
Looks good to me! Would pull, but I can't 😦

File: test/main-tests/test.js [hunk 1]
```diff
@@ -242,4 +242,22 @@ describe('EslintValidationFilter', function describeEslintValidationFilter() {
...
+      options: {
+        ignore: false,
+      },
+      throwOnError: true
+    })();
+
+    return promise.catch((err) => {
+      expect(err).to.be.an('error');
+      expect(err.message).to.equal('rules violation with `error` severity level');
+    });
```
Comment (Turbo87) [inline test/main-tests/test.js]: Note that the assertions won't run when the promise does not throw. Maybe we should use chai-as-promised here.

Comment (BrianSipple) [inline test/main-tests/test.js]: @Turbo87 I really like the idea of using `chai-as-promised`, but might it be better to explore that in a separate story around refactoring the larger test suite (which I definitely think we could stand to do anyway)?

I could refactor this block in the meantime like so:
```
  it('throws when `throwOnError` is set and result severity', function(done) {
    const promise = shouldReportErrors(FIXTURES, {
      options: {
        ignore: false,
      },
      throwOnError: true
    })();

    promise.then(
      null,
      (err) => {
        expect(err).to.be.an('error');
        expect(err.message).to.equal('rules violation with `error` severity level');
        done();
      }
    )
    .catch(err => done(err));
  });
```

Comment (Turbo87) [inline test/main-tests/test.js]: I think the current state is okay. Feel free to update it in a separate PR :)

**Comment by alexlafroscia** [comment]
@BrianSipple we should release a `2.5` that includes this as well, right?
